version: '3'
services:
  dinamo-database:
    container_name: dinamo-database
    image: postgres:10-alpine
    restart: always
    ports:
      - '47385:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dinamo-database
