version: '3.8'
services:
  dinamo-database:
    container_name: dinamo-database
    image: postgres:alpine
    restart: always
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dinamo-database
