version: '3.9'

services:
  dinamo-database:
    container_name: dinamo-database
    image: postgres:14.1-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dinamo-database
